version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  docker: circleci/docker@1.5.0
executors:
  docker-publisher:
   docker:
   - image: circleci/node:latest
     auth:
       username: $DOCKERHUB_USERNAME
       password: $DOCKERHUB_PASSWORD
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'
jobs:
  publishLatestToHub:
     executor: docker-publisher
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Publish Docker Image to Docker Hub
           command: |
             echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
             docker build -t ${DOCKERHUB_USERNAME}/$IMAGE_NAME:latest .
             docker push ${DOCKERHUB_USERNAME}/$IMAGE_NAME:latest
  say-hello:
     docker:
      - image: cimg/base:stable
     steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  maven_test:
    jobs:
      - maven/test:
          command: '-X compile test'
          executor: java17
  deploy:
    jobs:
      - publishLatestToHub
